### ISSUE TITLE
No Pura Aurora Linux build possible

### ISSUE THREAD

**Issue by finddabug** [pura-dev/pura-release#1]
As mentioned on the pura.one webpage the Aurora Dec. 20 release should also contain a Linux version. I unpacked the source code `.tar.gz` file only to find another Windows .exe file in it.
Also the release file `https://github.com/pura-dev/pura-release/archive/1.1.0.tar.gz` contains no source files for Linux.

**Comment by pura-admin** [comment]
Source code is now included in v1.1.1. Unfortunately, due to the complexity of the Electron build process, Linux support for Aurora has been pushed back until the early 2018 releases.
